### PR TITLE
Feature/readme update

### LINKED ISSUE #121: Update Readme to Current State
As of now, the Readme is not up to date with 2019.6 and it should be upgraded to fit the upcoming 2019.10 release.

### PR DESCRIPTION
**Pull request by lukasmweber**
Updates Readme to the current state, including updated installation instructions.

Any Remarks or stuff that needs to be changed/added @jahofmann @sommerlukas ?

Closes #121.

### CODE REVIEW

**Comment by jahofmann** [comment]
And try to use `git pull --rebase` instead of git pull to avoid those useless merge commits that cloud the history and have no actual information. I prefer to make this behavior default, as git pull with merge is pretty much never desired as shown in https://coderwall.com/p/yf5-0w/like-git-pull-rebase-make-it-default

**Comment by lukasmweber** [comment]
@jahofmann What steps are necessary to build the libraries if OS-Packages are used? Are there any?

**Comment by jahofmann** [comment]
> @jahofmann What steps are necessary to build the libraries if OS-Packages are used? Are there any?

There are two different OS-Packages. The first is for the toolflow and does not contain anything from the runtime (I guess that's what you refer to as libraries?)
The second is for the runtime and doesn't contain anything for the toolflow.

For neither, the user has to compile anything as they are precompiled for the corresponding distribution.

For the toolflow the setup script will be in /opt/tapasco/tapasco-init-toolflow.sh (iirc).

For the runtime the correct CMake etc directories of the OS should be used.

**Comment by jahofmann** [comment]
Please add "[skip ci]" inside the commit messages to avoid running pipelines without any changes that affect the pipeline.

**Comment by jahofmann** [comment]
Fixed the history to remove pointless merges from develop.

**Comment by lukasmweber** [comment]
@jahofmann please re-review, Links are now added.

**Comment by jahofmann** [comment]
Looks good, we have to make sure to change the links to the correct ones in the release branch (2019.10 package name).

**Pull request merged**
