### PR TITLE
Fix memory allocator

### PR DESCRIPTION
**Pull request by tsmk94**
Exit loop iterating over all free memory segments as soon as first matching memory segment has been found.

### CODE REVIEW

**Review by wirthjohannes — APPROVED** [review]

**Comment by jahofmann** [comment]
Isn't the `break` too far down and it will never loop more than once even if there are more free memory segments which could be of the right size?

To make the whole thing a bit cleaner you could do something like:
```rust
    fn allocate(&mut self, size: DeviceSize, _va: Option<u64>) -> Result<DeviceAddress> {
        if size == 0 {
            return Err(Error::InvalidSize { size });
        }
        trace!("Looking for free memory.");
        let size_aligned = self.fix_alignment(size);

        if let Some((i, s)) = self
            .memory_free
            .iter_mut()
            .enumerate()
            .filter(|(i, s)| s.size >= size_aligned)
            .next()
        {
            trace!("Found free space in segment {:?}.", s);
            let addr = s.base;
            self.memory_used.push(MemoryFree {
                base: addr,
                size: size_aligned,
            });
            s.size -= size_aligned;
            s.base += size_aligned;
            trace!("New segment is {:?}.", s);

            if s.size == 0 {
                trace!("Removing empty segment {:?}.", s);
                self.memory_free.remove(i);
            }

            Ok(addr)
        } else {
            Err(Error::OutOfMemory { size: size_aligned })
        }
    }
```

**Comment by tsmk94** [comment]
Why would you continue to search if you have found a matching segment?

**Comment by tsmk94** [comment]
I think I got your comment wrong....
Yes, you are right, the break is one bracket too far down.

**Comment by jahofmann** [comment]
Yes, that was what I was referring to :)

**Pull request merged**
